#ifndef __LED_H_
#define __LED_H_
#include "main.h"
#include "stm32f1xx.h"
#include "gpio.h"
//LED_SWITCH1
#define LED_SWITCH1_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH1_Pin,GPIO_PIN_SET)
#define LED_SWITCH1_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH1_Pin,GPIO_PIN_RESET)
//LED_SWITCH2
#define LED_SWITCH2_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH2_Pin,GPIO_PIN_SET)
#define LED_SWITCH2_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH2_Pin,GPIO_PIN_RESET)
//LED_SWITCH3
#define LED_SWITCH3_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH3_Pin,GPIO_PIN_SET)
#define LED_SWITCH3_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH3_Pin,GPIO_PIN_RESET)
//LED_SWITCH4
#define LED_SWITCH4_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH4_Pin,GPIO_PIN_SET)
#define LED_SWITCH4_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH4_Pin,GPIO_PIN_RESET)
//LED_SWITCH5
#define LED_SWITCH5_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH5_Pin,GPIO_PIN_SET)
#define LED_SWITCH5_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH5_Pin,GPIO_PIN_RESET)
//LED_SWITCH6
#define LED_SWITCH6_ON HAL_GPIO_WritePin(GPIOB,LED_SWITCH6_Pin,GPIO_PIN_SET)
#define LED_SWITCH6_OFF HAL_GPIO_WritePin(GPIOB,LED_SWITCH6_Pin,GPIO_PIN_RESET)

void LED_SWITCH(uint8_t num);
void TURN_OFF_LED(void);

#endif